### ISSUE TITLE
在使用Rpi zero w的retroflag gpi case中出现声音卡顿/gpi case zero w ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by kinkymouse** [sdlpal/sdlpal#167]
**Describe the bug / 描述问题**
在使用Rpi zero w的retroflag gpi case中出现声音卡顿/gpi case zero w 
when i run sdlpal in gpi case with Rpi 0w，audio lag， it reports this：
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred

**Environment (please complete the following information)环境（请提供如下信息）:**
 - OS系统: Raspbian lite 4.19
 - Device设备  Retroflag GPi case
 - Version版本 使用github sdlpal master.zip 在Gpi case机器系统中编译生成 / sudo make in Gpi case with github sdlpal master.zip 
[Gpi case(sdlpal).zip](https://github.com/sdlpal/sdlpal/files/3538385/Gpi.case.sdlpal.zip)

 - Resource游戏资源  DOS original with debug patch 3.1 /DOS修正3.1版/
 - Config配置  默认default 
[sdlpal.txt](https://github.com/sdlpal/sdlpal/files/3538388/sdlpal.txt)
KeepAspectRatio=1
FullScreen=0
LaunchSetting=0
Stereo=1
UseSurroundOPL=1
EnableKeyRepeat=0
UseTouchOverlay=0
EnableAviPlay=0
EnableGLSL=0
EnableHDR=0
SurroundOPLOffset=384
LogLevel=5
AudioDevice=-1
AudioBufferSize=1024
OPLSampleRate=49716
ResampleQuality=4
SampleRate=44100
MusicVolume=100
SoundVolume=100
WindowHeight=400
WindowWidth=640
TextureHeight=400
TextureWidth=640
CD=OGG
Music=RIX
OPLCore=DBFLT
OPLChip=OPL2

 - Verbose Log 详细日志文件 [ see [FAQ](../wiki) for steps; upload it here]

![image](https://user-images.githubusercontent.com/54507429/63653111-34ba6580-c79b-11e9-9125-fc5f80073db7.png)

**Additional context 其他上下文**
请在此追加觉得可能与此问题相关的任何细节。

**Comment by PalMusicFan** [comment]
Rpi zero w的性能是比较有限的。请使用以下设置测试，如果问题消失，可以尝试逐步调回高品质，找到合适的设置。
Rpi zero w is a device with limited performance. Please try the following settings. If the problem is solved, try to gradually return to high quality settings and find the best settings. 

UseSurroundOPL=0
ResampleQuality=2
OPLSampleRate=22050
OPLCore=MAME

**Comment by kinkymouse** [comment]
谢谢 我回去尝试一下 ！ 树莓派0的声音性能这么有限么？感觉有点吃惊…毕竟都2013年的电子产品了呢… 连一些山寨游戏机和很老的智能手机都能把sdlpal运行的很好 
many thx，I’ll try it later on.  Unbelievable，does RPi 0’s audio core reeeally so poor？ After all it’s a micro-pc designed in 2013 or so，cannot imagine RPi 0’s sdlpal running performance is just equal or even worse than what on some handmade/ko game console and cellphone s60v3 such as Nokia E63.

**Comment by PalMusicFan** [comment]
现在的SDLPal，因为追求准确的模拟和更好的播放效果，默认音频系统设置是很吃CPU的。据个人测试，PSV在333MHz下也不能满足默认设置的性能要求。
您还可以关注一下GLSL滤镜系统，那个可以很吃GPU的。
Because of the pursuit of accurate simulation and better playback, the default audio system settings of current SDLPal are very CPU consuming. According to my test result, even PSV can not meet the performance requirements of default settings at 333MHz.
You can also take a look at the GLSL filter system, that could be GPU consuming.

**Comment by kinkymouse** [comment]
谢谢 用您建议的设置，效果好了很多，但偶尔会有些卡。 自己又摸索了一下 调成如下了，极少卡顿了，感觉还不错： 
UseSurroundOPL=0
ResampleQuality=3
OPLSampleRate=22050
SampleRate=22050
OPLCore=DBFLT
其他的都是默认设置

**Comment by PalMusicFan** [comment]
好。如果您有兴趣，可否提供这些测试结果？
1. DBINT DBFLT MAME哪个核心最快？NUKED不用测，那个的设计目标是完全实现OPL3仿真。
2. OPLSampleRate使用24858或49716能否流畅播放？
3. 使用DBINT核心有没有程序随机出错的现象？ 
4. 声音卡顿的时候游戏操作会卡顿吗？ 
5. 什么设置下可以使用UseSurroundOPL=1且声音流畅 ？
非常感谢！
If you are interested, would you please provide these following test results?
1. DBINT DBFLT MAME, which core is the fastest? There is no need to test the NUKED core, since it is designed to fully simulate the OPL3 hardware. 
2. Could OPLSampleRate = 24858 (or 49716) be OK?
3. Is there a random crash when using the DBINT core?
4. When the sound is laggy, is the game play laggy too?
5. Is it possible to make the sound OK when using UseSurroundOPL=1?
Thank you very much!

**Comment by palxex** [comment]
Closing due to lack of response. Feel free replying.
