### ISSUE TITLE
Why not updating the latest build to Google Play Store?

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#177]
Dear Developer,

I am just wondering if we can upload the latest builds to Google Play Store every time they are ready.
It is much easier for us to update it instead of turning back to the bintray website to check if new builds are available.
If you don't want to upload "unstable" versions to the store, what if upload them to the test branch?
Thank you very much.

Best Regards,
Eric

**Comment by palxex** [comment]
Currently, every commit will generate a complete build, which can be much too frequency than nightly, I think @CecilHarvey does not have time on checking whether every of them is valuable for pushing to store.
Let's discuss whether there's a more feasible way on archiving it. After a big feature merged( like this time, opus), ask @CecilHarvey (for example, in this issue) push a test build? 
BTW, I think we'd better separate usage of nightly build( for SDLPal, on bintray ), testing release and stable release. For me, nightly is more suit for bleeding edge usage, bug checking( not every developer have every platform ), etc. Stable should be used for scheduled release( yes, I think we'd make a schedule, for example at least one or two per year ). Testing, IMHO should be used for preparing stable release, for example testing whether a big feature introduces new bugs. Since we've already have nightly, Do we REALLY need test build? It's not an automatically action, unlike push to bintray. Let's discuss it first.

**Comment by CecilHarvey** [comment]
Now Travis CI should upload APK to google play store (as alpha test version) for every commit.
Please reopen this issue and let me know if this does not work.

**Comment by palxex** [comment]
Great :)
