### ISSUE TITLE
Blank screen when enabling GLSL shaders

### ISSUE THREAD

**Issue by wn2000** [sdlpal/sdlpal#199]
Native build on a RK3328 Mali-450 platform (aarch64 Linux, GLES2, SDL2 with KMS/DRM).

The following changes were made for it to build:
- `unix/Makefile`: changed `-lGL` to `-lGLESv2`
- `mini_glloader.h`: made sure the following are enabled:
```
#define GLES 1
#undef FORCE_OPENGL_CORE_PROFILE
```

The issue:
Enabling any shader, including `plain.glsl`, causes the screen to go blank. The game seems to run fine in the background judging from music play and key presses, but the screen stays blank.

**Comment by palxex** [comment]
Looks like same problem on cubieboard, which GPU was malli400; on that devkit the problem was even stranger, same hardware, the android version runs well but linux GLES version black screen(the software-accelerated GL version no problem), seems the driver stack not works well, like reporting unsupported extension( not sure since I debugged that several years ago).
Anyway let’s record it, please enable logging in SDLPal.cfg and attach it here.

**Comment by wn2000** [comment]
Do I just set log level to 0? It doesn't seem to print anything...But I can try again.

**Comment by palxex** [comment]
Sure, log level 0 is most verbose.
For file logging please also add [LogFileName](https://github.com/sdlpal/sdlpal/blob/879e1e2b957823e00f921d2dba038e29126246fb/docs/sdlpal.cfg.example#L155).

**Comment by palxex** [comment]
Closing due to lack of response.
