### ISSUE TITLE
Release v2.0.2017.0521 Queries

### ISSUE THREAD

**Issue by Nostaljaded** [sdlpal/sdlpal#40]
Hi,

1. **Is there a 32bit release for WIN in the release thread? Which one?**
Would like to package that in the next ENG translation release, rather than using a self-compiled one for authenticity & smaller file size. Self-compiled comes at 10MB.

2. **'sdlpal.exe' in release thread does not show version on its window title** like the mingw build.
![1](https://cloud.githubusercontent.com/assets/28423237/26292373/f8c053ca-3ee7-11e7-89e1-8a67d5d2287b.png)

3. **Android - Is the below circled access really required?**
![2](https://cloud.githubusercontent.com/assets/28423237/26292398/21baeea2-3ee8-11e7-8d7b-e9e25dff93fd.png)

- Not comfortable granting identity access to a game...

Regards.

**Comment by louyihua** [comment]
For the first question, the `sdlpal.exe` is the win32/x86 release file. But this name will be changed into `sdlpal-win32.zip` when next release is available.
For the second question, it is a bug and is fixed in a56cc96.
For the third question, the permission request was added automatically by Android Studio when I added the configuration GUI. So I need sometime to confirm whether it is really required for the GUI to work properly.
