### ISSUE TITLE
A few layout problems. 

### ISSUE THREAD

**Issue by PalMusicFan** [sdlpal/sdlpal#7]
1. After choosing "旧的回忆", SAVE SLOTS stays even if player presses ESC. 
2. There is something wrong with update dialog rects. 
Please edit the WORDS Item No. 32 of the message file, like this:   
32=Improved
Then, check Li Xiaoyao's Lv UP dialog rects, please.

**Comment by palxex** [comment]
The first problem fixed in 1d4d774.
For the latter one, the current implementation of level up dialog only calculate width from the dialog body, and then calculate offset tweak to keep the dialog in center. It is possible to also consider the header - through completely rewrite the logic, but that maybe unnecessary, since the whole screen width is limited, we'd better don't assume that every single translation item has no limit.
